common:
  root_dir: "../Experiments/CelebA" # Root directory path
                                    # The paths listed below are relative to 'root_dir'. That is, if 'dir_1/dir_2' is specified below,
                                    # the actual path will be 'root_dir/dir_1/dir_2'.
logger:
  log_dir: "logs"                # Log directory path
  train_log_interval: 5          # Interval of epochs for logging training and validation losses
  experiment_name: "celeba"      # Experiment name for MLflow
  common_run_name: "pcs128_ssgm" # Common part of the run name for MLflow
                                 # A suffix '_train' is added at the end in the case of training, and '_infer' in the case of inference.
image:
  size: 64                 # Image size
  num_channels: 3          # Number of image channels
  train_dir: "image/train" # Path to the directory containing training images
  valid_dir: "image/valid" # Path to the directory containing validation images
  test_dir: "image/test"   # Path to the directory containing test images
scat:
  J: 3                    # Scale parameter of wavelet scattering
  batch_size: 256         # Batch size of input images for wavelet scattering
  train_dir: "scat/train" # Path to the directory containing scattering coefficients of training images
  valid_dir: "scat/valid" # Path to the directory containing scattering coefficients of validation images
  test_dir: "scat/test"   # Path to the directory containing scattering coefficients of test images
pca:
  pcs_dim: 128                        # Dimension of the principal components
  comp_std_1st: 0.1                   # Standard deviation of the Gaussian random variable for the first principal component in the proposed model
  algorithm: "ipca"                   # 'pca' if applying PCA, or 'ipca' for Incremental PCA
  obj_file: "scatpcs/ipca_params.pkl" # Path to the PCA or Incremental PCA parameter file
  comp_std_file: "comp_stds.pth"      # Standard deviations of Gaussian random variables in the proposed model
  batch_size: 10000                   # Batch size of inputs to Incremental PCA
  train_pcs_dir: "scatpcs/train"      # Principal component scores of the training scattering coefficients
  valid_pcs_dir: "scatpcs/valid"      # Principal component scores of the validation scattering coefficients
  test_pcs_dir: "scatpcs/test"        # Principal component scores of the test scattering coefficients
generator:
  input_size: 4                       # Size of the input tensor to the CNN in the generator
  num_final_channels: 32              # Number of channels in the input tensor to the final layer of the generator
  checkpoint_dir: "model_checkpoints" # Path to the directory where the trained model parameters are saved
  batch_size: 64                      # Batch size of input images for training the generator
  num_epochs: 100                     # Number of epochs for training
  shuffle:                            # DataLoader argument: 'True' if the data should be reshuffled at every epoch, 'False' or leave it blank otherwise.
  lr: 0.001                           # Learning rate
  num_workers: 8                      # DataLoader argument: Number of subprocesses for data loading. Use '0' to load data in the main process.
infer:
  generated_image_dir: "generated_images" # Path to the directory where images generated by the trained generator from random numbers are saved
  recons_input_image_dir: "recons_inputs" # Path to the directory containing input images for reconstruction
  recons_output_dir: "recons_outputs"     # Path to the directory where images reconstructed by the trained generator are saved